import type { ProgrammeWithModules, RoadmapModuleWithProgress, RoadmapResource } from '@/types/roadmap';

// ─── Programme IDs ──────────────────────────────────────────────────────────

const SEEDLYFE_ID = 'prog-seedlyfe';
const SPROUTLYFE_ID = 'prog-sproutlyfe';

// ─── SeedLYFE Modules ───────────────────────────────────────────────────────

const SEEDLYFE_MODULES: RoadmapModuleWithProgress[] = [
    {
        id: 'sm-01',
        programme_id: SEEDLYFE_ID,
        title: 'VARK',
        description:
            'Discover your learning style using the VARK framework. Understand how you best absorb information to accelerate your development.',
        learning_objectives:
            'Identify your primary learning modality\nApply VARK strategies to self-study\nOptimise your training approach',
        module_type: 'training',
        display_order: 0,
        is_active: true,
        is_required: true,
        estimated_minutes: 30,
        exam_paper_id: null,
        icon_name: 'eye-outline',
        icon_color: '#007AFF',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: {
            id: 'p1',
            candidate_id: 'mock-candidate',
            module_id: 'sm-01',
            status: 'completed',
            completed_at: '2026-02-15T10:00:00Z',
            completed_by: 'mock-candidate',
            score: null,
            notes: null,
            updated_at: '2026-02-15T10:00:00Z',
            created_at: '2026-02-15T10:00:00Z',
        },
        resources: [],
        isLocked: false,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-02',
        programme_id: SEEDLYFE_ID,
        title: 'Enneagram',
        description:
            'Understand your personality type through the Enneagram system. Build self-awareness and improve interpersonal effectiveness.',
        learning_objectives:
            'Identify your Enneagram type\nUnderstand growth and stress patterns\nApply insights to client relationships',
        module_type: 'training',
        display_order: 1,
        is_active: true,
        is_required: true,
        estimated_minutes: 45,
        exam_paper_id: null,
        icon_name: 'people-outline',
        icon_color: '#AF52DE',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: {
            id: 'p2',
            candidate_id: 'mock-candidate',
            module_id: 'sm-02',
            status: 'completed',
            completed_at: '2026-02-20T14:00:00Z',
            completed_by: 'mock-candidate',
            score: null,
            notes: null,
            updated_at: '2026-02-20T14:00:00Z',
            created_at: '2026-02-20T14:00:00Z',
        },
        resources: [],
        isLocked: false,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-03',
        programme_id: SEEDLYFE_ID,
        title: 'Personal Branding',
        description:
            'Craft your professional identity. Learn to present yourself with confidence and authenticity in the financial advisory space.',
        learning_objectives:
            'Define your personal brand statement\nBuild a professional social media presence\nDevelop an elevator pitch',
        module_type: 'training',
        display_order: 2,
        is_active: true,
        is_required: true,
        estimated_minutes: 40,
        exam_paper_id: null,
        icon_name: 'star-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: {
            id: 'p3',
            candidate_id: 'mock-candidate',
            module_id: 'sm-03',
            status: 'in_progress',
            completed_at: null,
            completed_by: null,
            score: null,
            notes: null,
            updated_at: '2026-03-01T09:00:00Z',
            created_at: '2026-03-01T09:00:00Z',
        },
        resources: [],
        isLocked: false,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-04',
        programme_id: SEEDLYFE_ID,
        title: 'Personal Grooming',
        description: 'Master professional presentation standards. First impressions matter in client-facing roles.',
        learning_objectives:
            'Professional dress code standards\nMeeting presentation etiquette\nVirtual meeting appearance guidelines',
        module_type: 'training',
        display_order: 3,
        is_active: true,
        is_required: true,
        estimated_minutes: 25,
        exam_paper_id: null,
        icon_name: 'shirt-outline',
        icon_color: '#5856D6',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: false,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-05',
        programme_id: SEEDLYFE_ID,
        title: 'Tax',
        description: 'Understand Singapore tax fundamentals relevant to insurance and financial planning.',
        learning_objectives:
            'Personal income tax basics\nTax relief for insurance products\nSRS and CPF tax implications',
        module_type: 'training',
        display_order: 4,
        is_active: true,
        is_required: true,
        estimated_minutes: 60,
        exam_paper_id: null,
        icon_name: 'calculator-outline',
        icon_color: '#34C759',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-06',
        programme_id: SEEDLYFE_ID,
        title: 'CPF',
        description:
            'Master the Central Provident Fund system. Essential knowledge for advising clients on retirement and housing.',
        learning_objectives:
            'CPF account structure and allocation rates\nCPF investment scheme\nCPF Life and retirement adequacy',
        module_type: 'training',
        display_order: 5,
        is_active: true,
        is_required: true,
        estimated_minutes: 55,
        exam_paper_id: null,
        icon_name: 'wallet-outline',
        icon_color: '#007AFF',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-07',
        programme_id: SEEDLYFE_ID,
        title: 'MAP Calculation / Credit System',
        description:
            'Learn the Monthly Allowance Programme and credit system. Understand how your production translates to income.',
        learning_objectives: 'MAP calculation formula\nCredit system mechanics\nIncome projection planning',
        module_type: 'training',
        display_order: 6,
        is_active: true,
        is_required: true,
        estimated_minutes: 35,
        exam_paper_id: null,
        icon_name: 'trending-up-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-08',
        programme_id: SEEDLYFE_ID,
        title: 'Telemarketing',
        description:
            'Develop effective telephone prospecting skills. Learn scripts, objection handling, and appointment setting.',
        learning_objectives:
            'Cold calling frameworks\nObjection handling techniques\nAppointment-setting scripts\nCompliance in phone outreach',
        module_type: 'training',
        display_order: 7,
        is_active: true,
        is_required: true,
        estimated_minutes: 50,
        exam_paper_id: null,
        icon_name: 'call-outline',
        icon_color: '#34C759',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-09',
        programme_id: SEEDLYFE_ID,
        title: 'Money Instruments',
        description:
            'Overview of financial instruments: savings, fixed deposits, bonds, equities, unit trusts, and insurance products.',
        learning_objectives:
            'Asset class characteristics\nRisk-return spectrum\nInsurance as a financial instrument\nSuitability assessment basics',
        module_type: 'training',
        display_order: 8,
        is_active: true,
        is_required: true,
        estimated_minutes: 45,
        exam_paper_id: null,
        icon_name: 'cash-outline',
        icon_color: '#5856D6',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sm-10',
        programme_id: SEEDLYFE_ID,
        title: 'Prospecting / MySeminar',
        description: 'Master prospecting strategies and the MySeminar system for building your client pipeline.',
        learning_objectives:
            'Prospecting methods and channels\nMySeminar event planning\nLead generation and qualification\nFollow-up best practices',
        module_type: 'training',
        display_order: 9,
        is_active: true,
        is_required: true,
        estimated_minutes: 50,
        exam_paper_id: null,
        icon_name: 'megaphone-outline',
        icon_color: '#FF3B30',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    // ─── SeedLYFE Exams ─────────────────────────────────────────────────────
    {
        id: 'se-01',
        programme_id: SEEDLYFE_ID,
        title: 'RES5 Exam',
        description: 'Rules and Ethics of Financial Advisory Services. Mandatory SCI examination.',
        learning_objectives: null,
        module_type: 'exam',
        display_order: 10,
        is_active: true,
        is_required: true,
        estimated_minutes: 120,
        exam_paper_id: 'exam-res5',
        icon_name: 'school-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: { code: 'RES5', title: 'Rules & Ethics of Financial Advisory Services', pass_percentage: 70 },
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'se-02',
        programme_id: SEEDLYFE_ID,
        title: 'M9 Exam',
        description: 'Life Insurance and Investment-Linked Policies. Mandatory SCI examination.',
        learning_objectives: null,
        module_type: 'exam',
        display_order: 11,
        is_active: true,
        is_required: true,
        estimated_minutes: 120,
        exam_paper_id: 'exam-m9',
        icon_name: 'school-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: { code: 'M9', title: 'Life Insurance & Investment-Linked Policies', pass_percentage: 70 },
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'se-03',
        programme_id: SEEDLYFE_ID,
        title: 'M9A Exam',
        description: 'Health Insurance. Mandatory SCI examination.',
        learning_objectives: null,
        module_type: 'exam',
        display_order: 12,
        is_active: true,
        is_required: true,
        estimated_minutes: 90,
        exam_paper_id: 'exam-m9a',
        icon_name: 'school-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: { code: 'M9A', title: 'Health Insurance', pass_percentage: 70 },
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'se-04',
        programme_id: SEEDLYFE_ID,
        title: 'HI Exam',
        description: 'Health Insurance Module. Mandatory SCI examination.',
        learning_objectives: null,
        module_type: 'exam',
        display_order: 13,
        is_active: true,
        is_required: true,
        estimated_minutes: 90,
        exam_paper_id: 'exam-hi',
        icon_name: 'school-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: { code: 'HI', title: 'Health Insurance', pass_percentage: 70 },
        prerequisiteIds: [],
        isArchived: false,
    },
];

// ─── SproutLYFE Modules ─────────────────────────────────────────────────────

const SPROUTLYFE_MODULES: RoadmapModuleWithProgress[] = [
    {
        id: 'sp-01',
        programme_id: SPROUTLYFE_ID,
        title: 'Project 100 / First 9 in 90',
        description: 'Launch your practice with the Project 100 framework. Close your first 9 cases within 90 days.',
        learning_objectives:
            'Build your initial prospect list of 100\nSet 90-day production targets\nWeekly activity planning\nAccountability framework',
        module_type: 'training',
        display_order: 0,
        is_active: true,
        is_required: true,
        estimated_minutes: 60,
        exam_paper_id: null,
        icon_name: 'rocket-outline',
        icon_color: '#FF3B30',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-02',
        programme_id: SPROUTLYFE_ID,
        title: 'Business Ethics',
        description: 'Ethical standards in financial advisory. Compliance, market conduct, and professional integrity.',
        learning_objectives:
            'MAS regulations overview\nBest interest duty\nConflict of interest management\nComplaint handling',
        module_type: 'training',
        display_order: 1,
        is_active: true,
        is_required: true,
        estimated_minutes: 40,
        exam_paper_id: null,
        icon_name: 'shield-checkmark-outline',
        icon_color: '#007AFF',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-03',
        programme_id: SPROUTLYFE_ID,
        title: 'MAP Calculation / Credit System',
        description: 'Advanced MAP and credit system mastery. Optimise your production and income targets.',
        learning_objectives:
            'Advanced MAP scenarios\nCredit optimisation strategies\nBonus and incentive calculation\nAnnual income planning',
        module_type: 'training',
        display_order: 2,
        is_active: true,
        is_required: true,
        estimated_minutes: 45,
        exam_paper_id: null,
        icon_name: 'trending-up-outline',
        icon_color: '#34C759',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-04',
        programme_id: SPROUTLYFE_ID,
        title: 'Goal Setting',
        description: 'Strategic goal-setting for your advisory career. Quarterly and annual planning frameworks.',
        learning_objectives:
            'SMART goal framework\nQuarterly OKR planning\nActivity-based goal tracking\nReview and adjustment processes',
        module_type: 'training',
        display_order: 3,
        is_active: true,
        is_required: true,
        estimated_minutes: 35,
        exam_paper_id: null,
        icon_name: 'flag-outline',
        icon_color: '#AF52DE',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-05',
        programme_id: SPROUTLYFE_ID,
        title: 'PAC / PW',
        description: 'Prudential Assurance Company and PruWealth product training.',
        learning_objectives:
            'PAC product suite\nPruWealth features and benefits\nClient suitability assessment\nSales presentation techniques',
        module_type: 'training',
        display_order: 4,
        is_active: true,
        is_required: true,
        estimated_minutes: 50,
        exam_paper_id: null,
        icon_name: 'briefcase-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-06',
        programme_id: SPROUTLYFE_ID,
        title: 'PVA / PVW',
        description: 'PruVantage products — advanced ILP and wealth accumulation solutions.',
        learning_objectives:
            'PVA and PVW product features\nFund selection guidance\nPortfolio review processes\nILP regulatory requirements',
        module_type: 'training',
        display_order: 5,
        is_active: true,
        is_required: true,
        estimated_minutes: 50,
        exam_paper_id: null,
        icon_name: 'bar-chart-outline',
        icon_color: '#5856D6',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-07',
        programme_id: SPROUTLYFE_ID,
        title: 'PIIB / PILI',
        description: 'Prudential income and legacy products. Protection-focused solutions.',
        learning_objectives:
            'PIIB product structure\nPILI product structure\nNeeds-based selling\nCase study presentations',
        module_type: 'training',
        display_order: 6,
        is_active: true,
        is_required: true,
        estimated_minutes: 45,
        exam_paper_id: null,
        icon_name: 'umbrella-outline',
        icon_color: '#007AFF',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-08',
        programme_id: SPROUTLYFE_ID,
        title: 'Whole Life / Term / Pruman / PruLady',
        description: 'Core life insurance product suite. Whole life, term, and gender-specific plans.',
        learning_objectives:
            'Whole life vs term comparison\nPruman and PruLady features\nPremium and benefit calculations\nPolicy illustration walkthrough',
        module_type: 'training',
        display_order: 7,
        is_active: true,
        is_required: true,
        estimated_minutes: 55,
        exam_paper_id: null,
        icon_name: 'heart-outline',
        icon_color: '#FF3B30',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-09',
        programme_id: SPROUTLYFE_ID,
        title: 'Prushield + PA',
        description: 'Health insurance: Prushield and Personal Accident product mastery.',
        learning_objectives:
            'Prushield plan types\nCoverage limits and riders\nPA product features\nClaim process guidance',
        module_type: 'training',
        display_order: 8,
        is_active: true,
        is_required: true,
        estimated_minutes: 50,
        exam_paper_id: null,
        icon_name: 'medkit-outline',
        icon_color: '#34C759',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-10',
        programme_id: SPROUTLYFE_ID,
        title: 'Roadshow / Prospecting',
        description: 'Advanced roadshow execution and prospecting techniques. Field-ready skills.',
        learning_objectives:
            'Roadshow setup and logistics\nBooth engagement techniques\nLead capture and qualification\nPost-event follow-up system',
        module_type: 'training',
        display_order: 9,
        is_active: true,
        is_required: true,
        estimated_minutes: 45,
        exam_paper_id: null,
        icon_name: 'storefront-outline',
        icon_color: '#FF9500',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
    {
        id: 'sp-11',
        programme_id: SPROUTLYFE_ID,
        title: 'Financial Planning Concepts',
        description: 'Holistic financial planning framework. Bring it all together for comprehensive client advisory.',
        learning_objectives:
            'Financial needs analysis\nRetirement planning\nEstate planning basics\nComprehensive case study',
        module_type: 'training',
        display_order: 10,
        is_active: true,
        is_required: true,
        estimated_minutes: 60,
        exam_paper_id: null,
        icon_name: 'analytics-outline',
        icon_color: '#5856D6',
        created_at: '2026-01-01T00:00:00Z',
        archived_at: null,
        archived_by: null,
        updated_at: '2026-01-01T00:00:00Z',
        progress: null,
        resources: [],
        isLocked: true,
        examPaper: null,
        prerequisiteIds: [],
        isArchived: false,
    },
];

// ─── Sample Resources ───────────────────────────────────────────────────────

export const MOCK_RESOURCES: Record<string, RoadmapResource[]> = {
    'sm-01': [
        {
            id: 'r-01',
            module_id: 'sm-01',
            title: 'VARK Questionnaire',
            description: 'Take the official VARK assessment to identify your learning style.',
            resource_type: 'link',
            content_url: 'https://vark-learn.com/the-vark-questionnaire/',
            content_text: null,
            display_order: 0,
            is_active: true,
            created_at: '2026-01-01T00:00:00Z',
        },
        {
            id: 'r-02',
            module_id: 'sm-01',
            title: 'Learning Styles Guide',
            description: 'Comprehensive guide to applying VARK in professional development.',
            resource_type: 'file',
            content_url: null,
            content_text: null,
            display_order: 1,
            is_active: true,
            created_at: '2026-01-01T00:00:00Z',
        },
    ],
    'sm-03': [
        {
            id: 'r-03',
            module_id: 'sm-03',
            title: 'Personal Brand Worksheet',
            description: 'Step-by-step worksheet to define your unique professional brand.',
            resource_type: 'file',
            content_url: null,
            content_text: null,
            display_order: 0,
            is_active: true,
            created_at: '2026-01-01T00:00:00Z',
        },
        {
            id: 'r-04',
            module_id: 'sm-03',
            title: 'LinkedIn Profile Best Practices',
            description: 'Video tutorial on crafting a professional LinkedIn presence.',
            resource_type: 'video',
            content_url: null,
            content_text: null,
            display_order: 1,
            is_active: true,
            created_at: '2026-01-01T00:00:00Z',
        },
    ],
};

// ─── Assembled Programmes ───────────────────────────────────────────────────

const completedSeedModules = SEEDLYFE_MODULES.filter((m) => m.progress?.status === 'completed' && m.is_required);

export const MOCK_PROGRAMMES: ProgrammeWithModules[] = [
    {
        id: SEEDLYFE_ID,
        slug: 'seedlyfe',
        title: 'SeedLYFE',
        description: 'Foundation programme for new candidates.',
        display_order: 0,
        icon_type: 'seedling',
        is_active: true,
        archived_at: null,
        archived_by: null,
        created_at: '2026-01-01T00:00:00Z',
        updated_at: '2026-01-01T00:00:00Z',
        modules: SEEDLYFE_MODULES,
        completedCount: completedSeedModules.length,
        totalCount: SEEDLYFE_MODULES.filter((m) => m.is_required).length,
        percentage: Math.round(
            (completedSeedModules.length / SEEDLYFE_MODULES.filter((m) => m.is_required).length) * 100,
        ),
        isLocked: false,
        manuallyUnlocked: false,
        unlockedByName: null,
    },
    {
        id: SPROUTLYFE_ID,
        slug: 'sproutlyfe',
        title: 'SproutLYFE',
        description: 'Advanced programme for licensed advisors.',
        display_order: 1,
        icon_type: 'sprout',
        is_active: true,
        archived_at: null,
        archived_by: null,
        created_at: '2026-01-01T00:00:00Z',
        updated_at: '2026-01-01T00:00:00Z',
        modules: SPROUTLYFE_MODULES,
        completedCount: 0,
        totalCount: SPROUTLYFE_MODULES.filter((m) => m.is_required).length,
        percentage: 0,
        isLocked: true,
        manuallyUnlocked: false,
        unlockedByName: null,
    },
];
